### ISSUE TITLE
gpt-neox models cannot be benchmarked

### ISSUE THREAD

**Issue by peter-sk** [saattrupdan/ScandEval#54]
I have trouble benchmarking GPT-NeoX models:
scandeval --model-id Isotonic/gpt_neox_225M --raise-errors
2023-04-12 12:13:42,013 [INFO] <scandeval.benchmarker>
↳ Benchmarking Isotonic/gpt_neox_225M on the truncated version of SweReC
Downloading (…)lve/main/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 677/677 [00:00<00:00, 79.3kB/s]
Downloading pytorch_model.bin: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 867M/867M [02:01<00:00, 7.11MB/s]
Downloading (…)okenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 261/261 [00:00<00:00, 222kB/s]
Downloading (…)olve/main/vocab.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 799k/799k [00:00<00:00, 1.12MB/s]
Downloading (…)olve/main/merges.txt: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 457k/457k [00:00<00:00, 1.41MB/s]
Downloading (…)/main/tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 2.11M/2.11M [00:00<00:00, 2.56MB/s]
Downloading (…)cial_tokens_map.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 99.0/99.0 [00:00<00:00, 69.7kB/s]
2023-04-12 12:15:54,792 [INFO] <scandeval.benchmark_dataset>
↳ The model has 152,445,952 parameters, a vocabulary size of 50,432 and a maximum sequence length of 2,048.
Benchmarking:   0%|                                                                                                                                      | 0/10 [00:05<?, ?it/s]
Traceback (most recent call last):s]
  File "/usr/local/bin/scandeval", line 8, in <module>
    sys.exit(benchmark())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/scandeval/cli.py", line 209, in benchmark
    benchmarker(model_id=model_ids, dataset=datasets)
  File "/usr/local/lib/python3.9/site-packages/scandeval/benchmarker.py", line 382, in __call__
    return self.benchmark(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/scandeval/benchmarker.py", line 189, in benchmark
    record = self._benchmark_single(
  File "/usr/local/lib/python3.9/site-packages/scandeval/benchmarker.py", line 376, in _benchmark_single
    raise e
  File "/usr/local/lib/python3.9/site-packages/scandeval/benchmarker.py", line 333, in _benchmark_single
    results, metadata_dict = dataset(model_id)
  File "/usr/local/lib/python3.9/site-packages/scandeval/benchmark_dataset.py", line 619, in __call__
    return self.benchmark(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/scandeval/benchmark_dataset.py", line 320, in benchmark
    bs, ga = handle_error(
  File "/usr/local/lib/python3.9/site-packages/scandeval/utils.py", line 212, in handle_error
    raise InvalidBenchmark(str(e))
scandeval.exceptions.InvalidBenchmark: shape '[32, 1050, 12, 255]' is invalid for input of size 103219200

**Comment by peter-sk** [comment]
With a Danish model I am currently training, I get even funnier errors.

(base) mbp16:ScandEval petersk$ scandeval --model-id peter-sk/gpt-neox-da --raise-errors
2023-04-12 12:08:22,414 [INFO] <scandeval.benchmarker>
↳ Benchmarking peter-sk/gpt-neox-da on the truncated version of SweReC
Downloading pytorch_model.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 2.93G/2.93G [07:07<00:00, 6.86MB/s]
Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 294/294 [00:00<00:00, 43.0kB/s]
Downloading (…)olve/main/vocab.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 828k/828k [00:00<00:00, 1.43MB/s]
Downloading (…)olve/main/merges.txt: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 487k/487k [00:00<00:00, 2.85MB/s]
Downloading (…)/main/tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 2.17M/2.17M [00:00<00:00, 2.71MB/s]
Downloading (…)in/added_tokens.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 27.0/27.0 [00:00<00:00, 14.2kB/s]
Downloading (…)cial_tokens_map.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 129/129 [00:00<00:00, 53.8kB/s]
2023-04-12 12:15:53,204 [INFO] <scandeval.benchmark_dataset>
↳ The model has 1,311,631,360 parameters, a vocabulary size of 50,304 and a maximum sequence length of -48,210.
Benchmarking:   0%|                                                                                                                                      | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/bin/scandeval", line 8, in <module>
    sys.exit(benchmark())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/scandeval/cli.py", line 209, in benchmark
    benchmarker(model_id=model_ids, dataset=datasets)
  File "/usr/local/lib/python3.9/site-packages/scandeval/benchmarker.py", line 382, in __call__
    return self.benchmark(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/scandeval/benchmarker.py", line 189, in benchmark
    record = self._benchmark_single(
  File "/usr/local/lib/python3.9/site-packages/scandeval/benchmarker.py", line 333, in _benchmark_single
    results, metadata_dict = dataset(model_id)
  File "/usr/local/lib/python3.9/site-packages/scandeval/benchmark_dataset.py", line 619, in __call__
    return self.benchmark(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/scandeval/benchmark_dataset.py", line 238, in benchmark
    prepared_train = self._preprocess_data(
  File "/usr/local/lib/python3.9/site-packages/scandeval/sequence_classification.py", line 74, in _preprocess_data
    tokenised = dataset.map(tokenise, batched=True, load_from_cache_file=False)
  File "/usr/local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2815, in map
    return self._map_single(
  File "/usr/local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 546, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 513, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/datasets/fingerprint.py", line 480, in wrapper
    out = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 3236, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/usr/local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 3112, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/usr/local/lib/python3.9/site-packages/scandeval/sequence_classification.py", line 72, in tokenise
    return tokenizer(examples["text"], truncation=True, padding=False)
  File "/usr/local/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2538, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/usr/local/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2624, in _call_one
    return self.batch_encode_plus(
  File "/usr/local/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2815, in batch_encode_plus
    return self._batch_encode_plus(
  File "/usr/local/lib/python3.9/site-packages/transformers/models/gpt2/tokenization_gpt2_fast.py", line 168, in _batch_encode_plus
    return super()._batch_encode_plus(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 420, in _batch_encode_plus
    self.set_truncation_and_padding(
  File "/usr/local/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 375, in set_truncation_and_padding
    self._tokenizer.enable_truncation(**target)
OverflowError: can't convert negative int to unsigned

**Comment by peter-sk** [comment]
> scandeval --model-id Isotonic/gpt_neox_225M --raise-errors
> ...
> scandeval.exceptions.InvalidBenchmark: shape '[32, 1050, 12, 255]' is invalid for input of size 103219200

What happens here is that the model has 12 attention heads and a hidden size of 1024. Thus, head_size is calculated as 1024 // 12 == 85. Then, 3 * head-size is not 256 but 255, giving the issue here.

I am not quite sure how this works in general. In https://github.com/EleutherAI/gpt-neox, the code checks that the hidden size is evenly divisible by the number of heads. 

Any ideas? Anyway, this is NOT a Scandinavian model and the issue is with the model and/or the transformers library. I will create an issue there.

**Comment by peter-sk** [comment]
> scandeval --model-id peter-sk/gpt-neox-da --raise-errors
> ...
>  ↳ The model has 1,311,631,360 parameters, a vocabulary size of 50,304 and a maximum sequence length of -48,210.
> ...
>  OverflowError: can't convert negative int to unsigned

First of all, the computation of the maximum sequence length subtracts the pad token id. This leads to a negative minimal length in model_loading. This is fixable by only calculating the remaining all_max_lengths when there is no such thing given for the model. But I am not sure this is a good fix, in general.
