### ISSUE TITLE
Not able to run scandeval with openai models

### ISSUE THREAD

**Issue by marcelcastrobr** [saattrupdan/ScandEval#65]
Hi, 
First of all, thanks for the scandeval benchmark. I was able to use hf models but not openai.
I see that openai is part of the leaderboard https://scandeval.github.io/mainland-nlu-benchmark/.

While running the following command I get the error below:
**$  scandeval --model-id gpt-3.5-turbo --dataset scandiqa-no**

2023-10-15 17:52:59.987573: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-10-15 17:53:01,516 [INFO] <scandeval.benchmarker>
↳ Benchmarking gpt-3.5-turbo on the Norwegian part of truncated version of ScandiQA
2023-10-15 17:53:02,847 [INFO] <scandeval.benchmarker>
↳ gpt-3.5-turbo could not be benchmarked on the Norwegian part of truncated version of ScandiQA. Skipping.

Could you guide me on what I am doing wrong?

**Comment by marcelcastrobr** [comment]
running with --raise-errors, I see that it is trying to use HF Hub.

**$scandeval --model-id openai/gpt-3.5-turbo --dataset scandiqa-no --raise-errors**

2023-10-15 17:55:35.339737: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-10-15 17:55:36,865 [INFO] <scandeval.benchmarker>
↳ Benchmarking openai/gpt-3.5-turbo on the Norwegian part of truncated version of ScandiQA
Traceback (most recent call last):
  File "/opt/tensorflow/bin/scandeval", line 8, in <module>
    sys.exit(benchmark())
  File "/opt/tensorflow/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/tensorflow/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/tensorflow/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/tensorflow/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/tensorflow/lib/python3.10/site-packages/scandeval/cli.py", line 209, in benchmark
    benchmarker(model_id=model_ids, dataset=datasets)
  File "/opt/tensorflow/lib/python3.10/site-packages/scandeval/benchmarker.py", line 382, in __call__
    return self.benchmark(*args, **kwargs)
  File "/opt/tensorflow/lib/python3.10/site-packages/scandeval/benchmarker.py", line 189, in benchmark
    record = self._benchmark_single(
  File "/opt/tensorflow/lib/python3.10/site-packages/scandeval/benchmarker.py", line 351, in _benchmark_single
    raise e
  File "/opt/tensorflow/lib/python3.10/site-packages/scandeval/benchmarker.py", line 333, in _benchmark_single
    results, metadata_dict = dataset(model_id)
  File "/opt/tensorflow/lib/python3.10/site-packages/scandeval/benchmark_dataset.py", line 628, in __call__
    return self.benchmark(*args, **kwargs)
  File "/opt/tensorflow/lib/python3.10/site-packages/scandeval/benchmark_dataset.py", line 180, in benchmark
    model_config = model_configurator(
  File "/opt/tensorflow/lib/python3.10/site-packages/scandeval/hf_hub.py", line 84, in get_model_config
    raise InvalidBenchmark(
scandeval.exceptions.InvalidBenchmark: The model openai/gpt-3.5-turbo does not exist on the Hugging Face Hub.

**Comment by saattrupdan** [comment]
Hey! The OpenAI support is not in a released version of ScandEval yet, but you can use it if you install from source: `pip install git+https://github.com/saattrupdan/scandeval` 🙂

If it doesn't work then let me know!

**Comment by saattrupdan** [comment]
Closing this - feel free to reopen if it didn't fix your issue 🙂
